services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"
    volumes:
      - dataVolumes:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: 123456aA@
      MINIO_ROOT_PASSWORD: 123456aA@
    command: server --console-address ":9001" /data
volumes:
  dataVolumes:
