
spring:
  application:
    name: demo
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_spring?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    sender: duong2lophot@gmail.com
    password: wqnhtkxxzsndzuyb
    receiver: duong2lophot@gmail.com
  jwt:
    secretKey_access_token: Gd7Jf9vZsPiZhvQ5l3X8mYvR6P8jTv1L2xQ6jYuTzWvR5dMfH2k7gQ==
    secretKey_refresh_token: Gd8Jf9vZsPiZhvQ5l3X8mYvR6P8jTv1L2xQ6jYuTzWvR5dMfH2k7gQ==
  minio:
    secretKey_minio: YlmOLU56Q8LCnDv6msAkVLzFNzhdGoHm2C5DFpld
    accessKey_minio: J3xLDIlgcn9Utz22BIv8
    url: http://localhost:9000
    bucket_name: upload-file
  kafka:
    bootstrap-servers: localhost:29092
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li7nDlXkoHeYH2k1
            client-secret: 41b1323a6e8db9efd31c860b0e06943f1f20bfb6
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/api/v1/home"
          google:
            clientId: 192059546744-rudedb1b7jbq28cj8dd5pbic9redjpi5.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/v1/home"
server:
  port: 5000
